# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Shirage_Project\YT - PlaylistAPP\workspace\Source_fix_2.0\Source_Ui\UI_Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(664, 712)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.wgt_Right = QtWidgets.QWidget(self.centralwidget)
        self.wgt_Right.setGeometry(QtCore.QRect(610, 120, 51, 145))
        self.wgt_Right.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 106, 116);\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"}")
        self.wgt_Right.setObjectName("wgt_Right")
        self.btn_SequentialPlayVideo = QtWidgets.QPushButton(self.wgt_Right)
        self.btn_SequentialPlayVideo.setGeometry(QtCore.QRect(10, 35, 31, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_SequentialPlayVideo.sizePolicy().hasHeightForWidth())
        self.btn_SequentialPlayVideo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        self.btn_SequentialPlayVideo.setFont(font)
        self.btn_SequentialPlayVideo.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: transparent;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"border:3px solid;\n"
"border-color: rgb(255, 14, 18);\n"
"}")
        self.btn_SequentialPlayVideo.setIconSize(QtCore.QSize(16, 16))
        self.btn_SequentialPlayVideo.setObjectName("btn_SequentialPlayVideo")
        self.lbl_SequentialPlayVideo = QtWidgets.QLabel(self.wgt_Right)
        self.lbl_SequentialPlayVideo.setGeometry(QtCore.QRect(9, 10, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        self.lbl_SequentialPlayVideo.setFont(font)
        self.lbl_SequentialPlayVideo.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: transparent;\n"
"border-top-left-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"}")
        self.lbl_SequentialPlayVideo.setObjectName("lbl_SequentialPlayVideo")
        self.wgt_Center = QtWidgets.QWidget(self.centralwidget)
        self.wgt_Center.setGeometry(QtCore.QRect(0, 0, 611, 671))
        self.wgt_Center.setMouseTracking(False)
        self.wgt_Center.setStyleSheet("QWidget#wgt_Center{\n"
"background-color:#003D79;\n"
"border:5px solid #515151;\n"
"border-top-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"}")
        self.wgt_Center.setObjectName("wgt_Center")
        self.btn_max = QtWidgets.QPushButton(self.wgt_Center)
        self.btn_max.setGeometry(QtCore.QRect(520, 0, 31, 41))
        self.btn_max.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.btn_max.setFont(font)
        self.btn_max.setStyleSheet("QPushButton#btn_max{color: #aaff00;border:none;background-color: transparent;}\n"
"\n"
"QPushButton#btn_max:hover{color:#55557f;}")
        self.btn_max.setObjectName("btn_max")
        self.btn_min = QtWidgets.QPushButton(self.wgt_Center)
        self.btn_min.setGeometry(QtCore.QRect(480, 0, 31, 41))
        self.btn_min.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.btn_min.setFont(font)
        self.btn_min.setStyleSheet("QPushButton#btn_min{color: #3db95a;border:none;background-color: transparent;}\n"
"\n"
"QPushButton#btn_min:hover{color:#55557f;}")
        self.btn_min.setObjectName("btn_min")
        self.btn_close = QtWidgets.QPushButton(self.wgt_Center)
        self.btn_close.setGeometry(QtCore.QRect(560, 0, 31, 41))
        self.btn_close.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.btn_close.setFont(font)
        self.btn_close.setStyleSheet("QPushButton#btn_close{color: #fe6a6d;border:none;background-color: transparent;}\n"
"\n"
"QPushButton#btn_close:hover{color:#55557f;}")
        self.btn_close.setObjectName("btn_close")
        self.lsw_VideoList = QtWidgets.QListWidget(self.wgt_Center)
        self.lsw_VideoList.setGeometry(QtCore.QRect(25, 95, 561, 431))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lsw_VideoList.sizePolicy().hasHeightForWidth())
        self.lsw_VideoList.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        self.lsw_VideoList.setFont(font)
        self.lsw_VideoList.setStyleSheet("QListWidget#lsw_VideoList{\n"
"background:rgb(255, 255, 255);\n"
"font: 75 14pt \"微軟正黑體\";\n"
"border:1px solid white;\n"
"border-bottom-left-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"}")
        self.lsw_VideoList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lsw_VideoList.setObjectName("lsw_VideoList")
        self.lbl_VideoListUrl = QtWidgets.QLabel(self.wgt_Center)
        self.lbl_VideoListUrl.setGeometry(QtCore.QRect(110, 430, 141, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_VideoListUrl.sizePolicy().hasHeightForWidth())
        self.lbl_VideoListUrl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        self.lbl_VideoListUrl.setFont(font)
        self.lbl_VideoListUrl.setStyleSheet("color: rgb(213, 213, 213);")
        self.lbl_VideoListUrl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_VideoListUrl.setObjectName("lbl_VideoListUrl")
        self.lbl_VideoUrl = QtWidgets.QLabel(self.wgt_Center)
        self.lbl_VideoUrl.setGeometry(QtCore.QRect(20, 530, 231, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_VideoUrl.sizePolicy().hasHeightForWidth())
        self.lbl_VideoUrl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        self.lbl_VideoUrl.setFont(font)
        self.lbl_VideoUrl.setStyleSheet("color: rgb(213, 213, 213);")
        self.lbl_VideoUrl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_VideoUrl.setScaledContents(False)
        self.lbl_VideoUrl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_VideoUrl.setWordWrap(True)
        self.lbl_VideoUrl.setIndent(-2)
        self.lbl_VideoUrl.setObjectName("lbl_VideoUrl")
        self.lbl_FileName = QtWidgets.QLabel(self.wgt_Center)
        self.lbl_FileName.setGeometry(QtCore.QRect(20, 69, 571, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        self.lbl_FileName.setFont(font)
        self.lbl_FileName.setStyleSheet("background-color: rgb(0, 93, 68);\n"
"color: rgb(213, 213, 213);\n"
"border:1px solid white;\n"
"border-top-left-radius:10px;\n"
"border-top-right-radius:10px;")
        self.lbl_FileName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_FileName.setObjectName("lbl_FileName")
        self.btn_File = QtWidgets.QPushButton(self.wgt_Center)
        self.btn_File.setGeometry(QtCore.QRect(20, 40, 115, 23))
        self.btn_File.setStyleSheet("QPushButton{\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 93, 68);\n"
"}")
        self.btn_File.setObjectName("btn_File")
        self.btn_Edit = QtWidgets.QPushButton(self.wgt_Center)
        self.btn_Edit.setGeometry(QtCore.QRect(135, 40, 115, 23))
        self.btn_Edit.setStyleSheet("QPushButton{\n"
"border-top-left-radius:0px;\n"
"border-bottom-left-radius:0px;\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 93, 68);\n"
"}")
        self.btn_Edit.setObjectName("btn_Edit")
        self.btn_cloud = QtWidgets.QPushButton(self.wgt_Center)
        self.btn_cloud.setGeometry(QtCore.QRect(250, 40, 115, 23))
        self.btn_cloud.setStyleSheet("\n"
"QPushButton{\n"
"border-top-left-radius:0px;\n"
"border-bottom-left-radius:0px;\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 93, 68);\n"
"}")
        self.btn_cloud.setObjectName("btn_cloud")
        self.btn_Create = QtWidgets.QPushButton(self.wgt_Center)
        self.btn_Create.setGeometry(QtCore.QRect(365, 40, 115, 23))
        self.btn_Create.setStyleSheet("QPushButton{\n"
"border-top-left-radius:0px;\n"
"border-bottom-left-radius:0px;\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 93, 68);\n"
"}")
        self.btn_Create.setObjectName("btn_Create")
        self.btn_About = QtWidgets.QPushButton(self.wgt_Center)
        self.btn_About.setGeometry(QtCore.QRect(480, 40, 112, 23))
        self.btn_About.setStyleSheet("QPushButton{\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 93, 68);\n"
"}")
        self.btn_About.setObjectName("btn_About")
        self.wgt_Tools = QtWidgets.QWidget(self.wgt_Center)
        self.wgt_Tools.setGeometry(QtCore.QRect(230, 200, 179, 161))
        self.wgt_Tools.setStyleSheet("QWidget#wgt_Tools{\n"
"background-color: #acacac;\n"
"border:5px solid #515151;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"}")
        self.wgt_Tools.setObjectName("wgt_Tools")
        self.btn_Act1 = QtWidgets.QPushButton(self.wgt_Tools)
        self.btn_Act1.setGeometry(QtCore.QRect(5, 5, 169, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.btn_Act1.setFont(font)
        self.btn_Act1.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"border:0px;\n"
"background-color: transparent;\n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #7c7c7c;\n"
"\n"
"}")
        self.btn_Act1.setObjectName("btn_Act1")
        self.btn_Act2 = QtWidgets.QPushButton(self.wgt_Tools)
        self.btn_Act2.setGeometry(QtCore.QRect(5, 35, 169, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.btn_Act2.setFont(font)
        self.btn_Act2.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"border:0px;\n"
"background-color: transparent;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #7c7c7c;\n"
"}")
        self.btn_Act2.setObjectName("btn_Act2")
        self.btn_Act3 = QtWidgets.QPushButton(self.wgt_Tools)
        self.btn_Act3.setGeometry(QtCore.QRect(5, 65, 169, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.btn_Act3.setFont(font)
        self.btn_Act3.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"border:0px;\n"
"background-color: transparent;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #7c7c7c;\n"
"}")
        self.btn_Act3.setObjectName("btn_Act3")
        self.btn_Act4 = QtWidgets.QPushButton(self.wgt_Tools)
        self.btn_Act4.setGeometry(QtCore.QRect(5, 95, 169, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.btn_Act4.setFont(font)
        self.btn_Act4.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"border:0px;\n"
"background-color: transparent;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #7c7c7c;\n"
"}")
        self.btn_Act4.setObjectName("btn_Act4")
        self.btn_Act5 = QtWidgets.QPushButton(self.wgt_Tools)
        self.btn_Act5.setGeometry(QtCore.QRect(5, 125, 169, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.btn_Act5.setFont(font)
        self.btn_Act5.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"border:0px;\n"
"background-color: transparent;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #7c7c7c;\n"
"}")
        self.btn_Act5.setObjectName("btn_Act5")
        self.btn_WgtClose = QtWidgets.QPushButton(self.wgt_Tools)
        self.btn_WgtClose.setGeometry(QtCore.QRect(155, 0, 20, 31))
        self.btn_WgtClose.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_WgtClose.setFont(font)
        self.btn_WgtClose.setStyleSheet("QPushButton#btn_WgtClose{color: #FFFFFF;border:none;background-color: transparent;}\n"
"\n"
"QPushButton#btn_WgtClose:hover{color:#55557f;}")
        self.btn_WgtClose.setObjectName("btn_WgtClose")
        self.frame = QtWidgets.QFrame(self.wgt_Center)
        self.frame.setGeometry(QtCore.QRect(20, 90, 571, 441))
        self.frame.setStyleSheet("QWidget{\n"
"background-color: #FFFFFF;\n"
"border-bottom-left-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_AddVideoListUrl = QtWidgets.QPushButton(self.wgt_Center)
        self.btn_AddVideoListUrl.setGeometry(QtCore.QRect(370, 630, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_AddVideoListUrl.sizePolicy().hasHeightForWidth())
        self.btn_AddVideoListUrl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.btn_AddVideoListUrl.setFont(font)
        self.btn_AddVideoListUrl.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.btn_AddVideoListUrl.setObjectName("btn_AddVideoListUrl")
        self.frame_3 = QtWidgets.QFrame(self.wgt_Center)
        self.frame_3.setGeometry(QtCore.QRect(470, 540, 120, 111))
        self.frame_3.setStyleSheet("color: rgb(50, 50, 75);\n"
"background-color: rgb(217, 217, 217);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"padding-left: 1px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.cbb_HotVideoCategories = QtWidgets.QComboBox(self.frame_3)
        self.cbb_HotVideoCategories.setEnabled(False)
        self.cbb_HotVideoCategories.setGeometry(QtCore.QRect(10, 30, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbb_HotVideoCategories.sizePolicy().hasHeightForWidth())
        self.cbb_HotVideoCategories.setSizePolicy(sizePolicy)
        self.cbb_HotVideoCategories.setStyleSheet("QComboBox\n"
"{\n"
"color: rgb(50, 50, 75);\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"padding-left: 10px;\n"
"}\n"
"QComboBox::drop-down:button\n"
"{\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"background-color: rgb(170, 170, 255);\n"
"}")
        self.cbb_HotVideoCategories.setObjectName("cbb_HotVideoCategories")
        self.cbb_HotVideoCategories.addItem("")
        self.lbl_HotVideo = QtWidgets.QLabel(self.frame_3)
        self.lbl_HotVideo.setGeometry(QtCore.QRect(10, 0, 71, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_HotVideo.sizePolicy().hasHeightForWidth())
        self.lbl_HotVideo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        self.lbl_HotVideo.setFont(font)
        self.lbl_HotVideo.setStyleSheet("")
        self.lbl_HotVideo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_HotVideo.setObjectName("lbl_HotVideo")
        self.btn_GetHotViedoList = QtWidgets.QPushButton(self.frame_3)
        self.btn_GetHotViedoList.setGeometry(QtCore.QRect(10, 70, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_GetHotViedoList.sizePolicy().hasHeightForWidth())
        self.btn_GetHotViedoList.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.btn_GetHotViedoList.setFont(font)
        self.btn_GetHotViedoList.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.btn_GetHotViedoList.setObjectName("btn_GetHotViedoList")
        self.checkBox_RandomAddingVideo = QtWidgets.QCheckBox(self.wgt_Center)
        self.checkBox_RandomAddingVideo.setGeometry(QtCore.QRect(370, 560, 91, 20))
        font = QtGui.QFont()
        font.setBold(False)
        self.checkBox_RandomAddingVideo.setFont(font)
        self.checkBox_RandomAddingVideo.setStyleSheet("color: rgb(213, 213, 213);")
        self.checkBox_RandomAddingVideo.setChecked(False)
        self.checkBox_RandomAddingVideo.setObjectName("checkBox_RandomAddingVideo")
        self.checkBox_AutoSelectVideo = QtWidgets.QCheckBox(self.wgt_Center)
        self.checkBox_AutoSelectVideo.setGeometry(QtCore.QRect(370, 540, 91, 20))
        font = QtGui.QFont()
        font.setBold(False)
        self.checkBox_AutoSelectVideo.setFont(font)
        self.checkBox_AutoSelectVideo.setStyleSheet("color: rgb(213, 213, 213);")
        self.checkBox_AutoSelectVideo.setObjectName("checkBox_AutoSelectVideo")
        self.btn_AddVideoUrl = QtWidgets.QPushButton(self.wgt_Center)
        self.btn_AddVideoUrl.setGeometry(QtCore.QRect(370, 600, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_AddVideoUrl.sizePolicy().hasHeightForWidth())
        self.btn_AddVideoUrl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.btn_AddVideoUrl.setFont(font)
        self.btn_AddVideoUrl.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.btn_AddVideoUrl.setObjectName("btn_AddVideoUrl")
        self.txt_VideoUrl = QtWidgets.QTextEdit(self.wgt_Center)
        self.txt_VideoUrl.setGeometry(QtCore.QRect(20, 560, 341, 91))
        self.txt_VideoUrl.setStyleSheet("color: rgb(50, 50, 75);\n"
"background-color: rgb(236, 236, 236);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"padding-left: 1px;")
        self.txt_VideoUrl.setObjectName("txt_VideoUrl")
        self.btn_max.raise_()
        self.btn_min.raise_()
        self.btn_close.raise_()
        self.lbl_VideoListUrl.raise_()
        self.lbl_VideoUrl.raise_()
        self.lbl_FileName.raise_()
        self.btn_File.raise_()
        self.btn_Edit.raise_()
        self.btn_cloud.raise_()
        self.btn_Create.raise_()
        self.btn_About.raise_()
        self.frame.raise_()
        self.lsw_VideoList.raise_()
        self.wgt_Tools.raise_()
        self.btn_AddVideoListUrl.raise_()
        self.frame_3.raise_()
        self.checkBox_RandomAddingVideo.raise_()
        self.checkBox_AutoSelectVideo.raise_()
        self.btn_AddVideoUrl.raise_()
        self.txt_VideoUrl.raise_()
        self.wgt_Bottom = QtWidgets.QWidget(self.centralwidget)
        self.wgt_Bottom.setGeometry(QtCore.QRect(0, 670, 611, 21))
        self.wgt_Bottom.setStyleSheet("QWidget{\n"
"background-color: #515151;\n"
"border-bottom-right-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"}")
        self.wgt_Bottom.setObjectName("wgt_Bottom")
        self.hs_Opacity = QtWidgets.QSlider(self.wgt_Bottom)
        self.hs_Opacity.setGeometry(QtCore.QRect(20, 0, 571, 22))
        self.hs_Opacity.setMinimum(1)
        self.hs_Opacity.setMaximum(10)
        self.hs_Opacity.setPageStep(1)
        self.hs_Opacity.setProperty("value", 9)
        self.hs_Opacity.setOrientation(QtCore.Qt.Horizontal)
        self.hs_Opacity.setObjectName("hs_Opacity")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 664, 22))
        self.menubar.setObjectName("menubar")
        self.menu_FileHandle = QtWidgets.QMenu(self.menubar)
        self.menu_FileHandle.setObjectName("menu_FileHandle")
        self.menu_ListHandle = QtWidgets.QMenu(self.menubar)
        self.menu_ListHandle.setObjectName("menu_ListHandle")
        self.menu_CloudHandle = QtWidgets.QMenu(self.menubar)
        self.menu_CloudHandle.setObjectName("menu_CloudHandle")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menubar)
        self.act_NewFile = QtWidgets.QAction(MainWindow)
        self.act_NewFile.setObjectName("act_NewFile")
        self.act_ReadFile = QtWidgets.QAction(MainWindow)
        self.act_ReadFile.setObjectName("act_ReadFile")
        self.act_SaveFile = QtWidgets.QAction(MainWindow)
        self.act_SaveFile.setObjectName("act_SaveFile")
        self.act_SaveNewFile = QtWidgets.QAction(MainWindow)
        self.act_SaveNewFile.setObjectName("act_SaveNewFile")
        self.act_CloseForm = QtWidgets.QAction(MainWindow)
        self.act_CloseForm.setObjectName("act_CloseForm")
        self.act_Cut = QtWidgets.QAction(MainWindow)
        self.act_Cut.setObjectName("act_Cut")
        self.act_Copy = QtWidgets.QAction(MainWindow)
        self.act_Copy.setObjectName("act_Copy")
        self.act_Paste = QtWidgets.QAction(MainWindow)
        self.act_Paste.setObjectName("act_Paste")
        self.act_Delete = QtWidgets.QAction(MainWindow)
        self.act_Delete.setObjectName("act_Delete")
        self.act_SelectAll = QtWidgets.QAction(MainWindow)
        self.act_SelectAll.setObjectName("act_SelectAll")
        self.act_Connect = QtWidgets.QAction(MainWindow)
        self.act_Connect.setObjectName("act_Connect")
        self.act_CreateNewListOnYoutube = QtWidgets.QAction(MainWindow)
        self.act_CreateNewListOnYoutube.setObjectName("act_CreateNewListOnYoutube")
        self.act_DeleteSpecificList = QtWidgets.QAction(MainWindow)
        self.act_DeleteSpecificList.setObjectName("act_DeleteSpecificList")
        self.act_InputAPIkey = QtWidgets.QAction(MainWindow)
        self.act_InputAPIkey.setObjectName("act_InputAPIkey")
        self.act_Txt = QtWidgets.QAction(MainWindow)
        self.act_Txt.setObjectName("act_Txt")
        self.act_Excel = QtWidgets.QAction(MainWindow)
        self.act_Excel.setObjectName("act_Excel")
        self.action_18 = QtWidgets.QAction(MainWindow)
        self.action_18.setObjectName("action_18")
        self.act_About = QtWidgets.QAction(MainWindow)
        self.act_About.setObjectName("act_About")
        self.menu_FileHandle.addAction(self.act_NewFile)
        self.menu_FileHandle.addAction(self.act_ReadFile)
        self.menu_FileHandle.addSeparator()
        self.menu_FileHandle.addAction(self.act_SaveFile)
        self.menu_FileHandle.addAction(self.act_SaveNewFile)
        self.menu_FileHandle.addSeparator()
        self.menu_FileHandle.addAction(self.act_CloseForm)
        self.menu_ListHandle.addAction(self.act_Cut)
        self.menu_ListHandle.addAction(self.act_Copy)
        self.menu_ListHandle.addAction(self.act_Paste)
        self.menu_ListHandle.addAction(self.act_Delete)
        self.menu_ListHandle.addAction(self.act_SelectAll)
        self.menu_CloudHandle.addAction(self.act_Connect)
        self.menu_CloudHandle.addSeparator()
        self.menu_CloudHandle.addAction(self.act_CreateNewListOnYoutube)
        self.menu_CloudHandle.addAction(self.act_DeleteSpecificList)
        self.menu_CloudHandle.addSeparator()
        self.menu_CloudHandle.addAction(self.act_InputAPIkey)
        self.menu_4.addAction(self.act_Txt)
        self.menu_4.addAction(self.act_Excel)
        self.menu_5.addAction(self.action_18)
        self.menu_5.addAction(self.act_About)
        self.menubar.addAction(self.menu_FileHandle.menuAction())
        self.menubar.addAction(self.menu_ListHandle.menuAction())
        self.menubar.addAction(self.menu_CloudHandle.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_SequentialPlayVideo.setText(_translate("MainWindow", "播"))
        self.lbl_SequentialPlayVideo.setText(_translate("MainWindow", " ▶"))
        self.btn_max.setText(_translate("MainWindow", "▬"))
        self.btn_min.setText(_translate("MainWindow", "▬"))
        self.btn_close.setText(_translate("MainWindow", "▬"))
        self.lbl_VideoListUrl.setText(_translate("MainWindow", "Youtube 清單連結cccccccccc："))
        self.lbl_VideoUrl.setText(_translate("MainWindow", "請輸入Youtube 影片/清單的ID/連結："))
        self.lbl_FileName.setText(_translate("MainWindow", "Youtube 影片清單［］"))
        self.btn_File.setText(_translate("MainWindow", "播放清單"))
        self.btn_Edit.setText(_translate("MainWindow", "編輯"))
        self.btn_cloud.setText(_translate("MainWindow", "Youtube 應用"))
        self.btn_Create.setText(_translate("MainWindow", "產生"))
        self.btn_About.setText(_translate("MainWindow", "說明"))
        self.btn_Act1.setText(_translate("MainWindow", "無"))
        self.btn_Act2.setText(_translate("MainWindow", "無"))
        self.btn_Act3.setText(_translate("MainWindow", "無"))
        self.btn_Act4.setText(_translate("MainWindow", "無"))
        self.btn_Act5.setText(_translate("MainWindow", "無"))
        self.btn_WgtClose.setText(_translate("MainWindow", "✖"))
        self.btn_AddVideoListUrl.setText(_translate("MainWindow", "新增清單"))
        self.cbb_HotVideoCategories.setItemText(0, _translate("MainWindow", "Loading...."))
        self.lbl_HotVideo.setText(_translate("MainWindow", " 今日熱門："))
        self.btn_GetHotViedoList.setText(_translate("MainWindow", "搜尋"))
        self.checkBox_RandomAddingVideo.setText(_translate("MainWindow", "亂序新增影片"))
        self.checkBox_AutoSelectVideo.setText(_translate("MainWindow", "自動選擇影片"))
        self.btn_AddVideoUrl.setText(_translate("MainWindow", "新增影片"))
        self.menu_FileHandle.setTitle(_translate("MainWindow", "播放清單"))
        self.menu_ListHandle.setTitle(_translate("MainWindow", "編輯"))
        self.menu_CloudHandle.setTitle(_translate("MainWindow", "雲端上傳"))
        self.menu_4.setTitle(_translate("MainWindow", "產生"))
        self.menu_5.setTitle(_translate("MainWindow", "說明"))
        self.act_NewFile.setText(_translate("MainWindow", "新建清單"))
        self.act_NewFile.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.act_ReadFile.setText(_translate("MainWindow", "開啟清單"))
        self.act_ReadFile.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.act_SaveFile.setText(_translate("MainWindow", "儲存清單"))
        self.act_SaveFile.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.act_SaveNewFile.setText(_translate("MainWindow", "另存清單到..."))
        self.act_CloseForm.setText(_translate("MainWindow", "關閉"))
        self.act_CloseForm.setShortcut(_translate("MainWindow", "Esc"))
        self.act_Cut.setText(_translate("MainWindow", "剪下"))
        self.act_Cut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.act_Copy.setText(_translate("MainWindow", "複製"))
        self.act_Copy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.act_Paste.setText(_translate("MainWindow", "貼上"))
        self.act_Paste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.act_Delete.setText(_translate("MainWindow", "刪除"))
        self.act_Delete.setShortcut(_translate("MainWindow", "Del"))
        self.act_SelectAll.setText(_translate("MainWindow", "全部選取"))
        self.act_SelectAll.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.act_Connect.setText(_translate("MainWindow", "登入 Youtube 帳號"))
        self.act_Connect.setShortcut(_translate("MainWindow", "="))
        self.act_CreateNewListOnYoutube.setText(_translate("MainWindow", "建立新的 Youtube 清單"))
        self.act_CreateNewListOnYoutube.setShortcut(_translate("MainWindow", "F1"))
        self.act_DeleteSpecificList.setText(_translate("MainWindow", "刪除指定清單"))
        self.act_DeleteSpecificList.setShortcut(_translate("MainWindow", "F2"))
        self.act_InputAPIkey.setText(_translate("MainWindow", "安裝 ODBC Driver 17 for SQL Server"))
        self.act_Txt.setText(_translate("MainWindow", "導出Txt文件"))
        self.act_Txt.setShortcut(_translate("MainWindow", "Ctrl+F1"))
        self.act_Excel.setText(_translate("MainWindow", "導出Excel文件"))
        self.act_Excel.setShortcut(_translate("MainWindow", "Ctrl+F2"))
        self.action_18.setText(_translate("MainWindow", "檢視說明"))
        self.act_About.setText(_translate("MainWindow", "關於Youtube播放工具"))
        self.act_About.setShortcut(_translate("MainWindow", "`"))
