# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Shirage_Project\YT - PlaylistAPP\workspace\Source_fix_2.0\Source_Ui\UI_VideoList.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListWindows(object):
    def setupUi(self, ListWindows):
        ListWindows.setObjectName("ListWindows")
        ListWindows.resize(762, 700)
        self.wgt_Top = QtWidgets.QWidget(ListWindows)
        self.wgt_Top.setGeometry(QtCore.QRect(0, 0, 761, 651))
        self.wgt_Top.setStyleSheet("QWidget#wgt_Top{\n"
"    background:#003d79;\n"
"border-top-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"}")
        self.wgt_Top.setObjectName("wgt_Top")
        self.frame = QtWidgets.QFrame(self.wgt_Top)
        self.frame.setGeometry(QtCore.QRect(30, 40, 701, 581))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color: rgb(198, 198, 198);\n"
"border:none;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px; \n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lsv_VideoList = QtWidgets.QListView(self.frame)
        self.lsv_VideoList.setGeometry(QtCore.QRect(30, 30, 641, 521))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lsv_VideoList.sizePolicy().hasHeightForWidth())
        self.lsv_VideoList.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.lsv_VideoList.setFont(font)
        self.lsv_VideoList.setStyleSheet("background-color: transparent;\n"
"border:none;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"\n"
"QListView::QScrollBar:horizontal \n"
"{\n"
"    border: 2px solid grey;\n"
"    background: #32CC99;\n"
"}")
        self.lsv_VideoList.setViewMode(QtWidgets.QListView.ListMode)
        self.lsv_VideoList.setObjectName("lsv_VideoList")
        self.btn_close = QtWidgets.QPushButton(self.wgt_Top)
        self.btn_close.setGeometry(QtCore.QRect(734, 0, 20, 31))
        self.btn_close.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_close.setFont(font)
        self.btn_close.setStyleSheet("QPushButton#btn_close{color: #FFFFFF;border:none;background-color: transparent;}\n"
"\n"
"QPushButton#btn_close:hover{color:#55557f;}")
        self.btn_close.setObjectName("btn_close")
        self.wgt_Buttom = QtWidgets.QWidget(ListWindows)
        self.wgt_Buttom.setGeometry(QtCore.QRect(0, 650, 761, 51))
        self.wgt_Buttom.setStyleSheet("QWidget#wgt_Buttom{\n"
"    background:#336666;\n"
"    border:1px solid white;\n"
"    border-bottom-left-radius:10px;\n"
"        border-bottom-right-radius:10px;\n"
"}")
        self.wgt_Buttom.setObjectName("wgt_Buttom")
        self.btn_Commit = QtWidgets.QPushButton(self.wgt_Buttom)
        self.btn_Commit.setGeometry(QtCore.QRect(570, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_Commit.setFont(font)
        self.btn_Commit.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    background-color: rgb(167, 205, 255);\n"
"    border:none;\n"
"    padding: 3px;\n"
"    font-family: \"Verdana\";\n"
"    font-size: 15px;\n"
"    text-align: center;\n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"    border-top-right-radius:10px;\n"
"    border-bottom-right-radius:10px;")
        self.btn_Commit.setObjectName("btn_Commit")
        self.btn_Cancel = QtWidgets.QPushButton(self.wgt_Buttom)
        self.btn_Cancel.setGeometry(QtCore.QRect(666, 10, 75, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_Cancel.setFont(font)
        self.btn_Cancel.setAutoFillBackground(False)
        self.btn_Cancel.setStyleSheet("color: rgb(255, 255, 255);\n"
"    background-color: rgb(167, 205, 255);\n"
"    border:none;\n"
"    padding: 3px;\n"
"    font-family: \"Verdana\";\n"
"    font-size: 15px;\n"
"    text-align: center;\n"
"border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"        border-bottom-right-radius:10px;")
        self.btn_Cancel.setObjectName("btn_Cancel")
        self.ckb_Check = QtWidgets.QCheckBox(self.wgt_Buttom)
        self.ckb_Check.setGeometry(QtCore.QRect(60, 1, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.ckb_Check.setFont(font)
        self.ckb_Check.setStyleSheet("")
        self.ckb_Check.setObjectName("ckb_Check")
        self.pb_Process = QtWidgets.QProgressBar(self.wgt_Buttom)
        self.pb_Process.setGeometry(QtCore.QRect(158, 8, 395, 25))
        self.pb_Process.setStyleSheet("QProgressBar {\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #05B8CC;\n"
"    width: 20px;\n"
"}\n"
"QProgressBar {\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}")
        self.pb_Process.setProperty("value", 0)
        self.pb_Process.setObjectName("pb_Process")

        self.retranslateUi(ListWindows)
        QtCore.QMetaObject.connectSlotsByName(ListWindows)

    def retranslateUi(self, ListWindows):
        _translate = QtCore.QCoreApplication.translate
        ListWindows.setWindowTitle(_translate("ListWindows", "影片列表"))
        self.btn_close.setText(_translate("ListWindows", "✖"))
        self.btn_Commit.setText(_translate("ListWindows", "OK"))
        self.btn_Cancel.setText(_translate("ListWindows", "Cancel"))
        self.ckb_Check.setText(_translate("ListWindows", "全選"))
